version: '3.7'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"  # Change the mapping to use port 8080 on the host

  solid-server:
    image: solidproject/community-server:latest
    ports:
      - "3000:3000"
    command: ["--baseUrl", "https://localhost:3000"]  # Set the correct base URL 
    environment:
      CSS_LOGGING_LEVEL: debug  # Adjust the log level as needed

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"  # Change the mapping to use port 8081 on the host
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    depends_on:
      - react-app
      - solid-server
