# Stage 1: Build the React app
FROM node:16 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Create a lightweight image to serve the app
FROM nginx:alpine

EXPOSE 80

COPY --from=build /app/dist /usr/share/nginx/html

# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]
