version: '3.7'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"

  solid-server:
    image: solidproject/community-server:6.0.0
    restart: always
    user: root
    ports:
      - "3000:3000"
    #volumes:
      #- /<path to volume>/solid-css/data:/data # Mount data directory
      #- /<path to config>/solid-css/config:/config # Mount config directory
      #- /<path to key>/ssl/server-key.pem:/home/user/ssl/private/key.pem # Mount SSL private key
      #- /<path to cert>/ssl/server-cert.pem:/home/user/ssl/certs/cert.pem # Mount SSL certificates
    #command: -c /config/pass-config.json -f /data -b https://opencommons.net  # Run with custom config
    #command: -f /data -b https://opencommons.net # Run with default config
  #nginx:
   # image: nginx:alpine
   # ports:
   #   - "8081:80"
   #volumes:
   # - ./config/nginx.conf:/etc/nginx/nginx.conf
   # - ./config/ssl:/etc/nginx/ssl

    #depends_on:
    #  - react-app
    #  - solid-server
