version: '3.8'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile.react # Creates new image for react app
    expose:
      - "8080" # Expose port for other services
    ports:
      - "8080:80"
    networks:
      - nginx_default

  solid-server:
    image: solidproject/community-server:latest # Use updated image or create using Dockerfile
    environment:
      - CSS_BASE_URL=https://css.opencommons.net
    restart: always
    user: root
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./data/solid-data:/data
      - ./config/solid-server/solid-config.json:/community-server/config/my-config.json
    networks:
      - nginx_default

  nginx-proxy-mgr:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data/nginx-proxy-mng-data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  nginx_default:

