version: '3.8'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile.react
    expose:
      - "8080" # Expose port for other services
    ports:
      - "8080:80"
    networks:
      - nginx_default

  solid-server:
    image: solidproject/community-server:6.0.0
    restart: always
    user: root
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./config/solid-server/solid-config.json:/home/node/.config/solid-server
      - ./data/solid-server:/home/node/.local/share/solid-server
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
